### PR TITLE
changed xaxis label for updated SESANS nomenclature from z to delta

### LINKED ISSUE #59: Update nomenclature for SESANS
This issue is an extension of the SasView issue 2663 at https://github.com/SasView/sasview/issues/2663 that requests an update to the nomenclature for SESANS data.

### PR DESCRIPTION
**Pull request by caitwolf**
This fixes #59 which is referencing the original SasView issue https://github.com/SasView/sasview/issues/2663. This only updates the label on the 1D plot. The residuals plot is fixed in a separate sasview PR (https://github.com/SasView/sasview/pull/2754).

### CODE REVIEW

**Comment by krzywon** [comment]
This seems reasonable so far. There are no new doc warnings, and the build failures match the failures already documented in #57.

**Comment by butlerpd** [comment]
assuming the corresponding sasview PR gets merged into 6.0.0 this will need to get merged into 0.9.0 as well

**Review by butlerpd — APPROVED** [review]
See review of paired PR in https://github.com/SasView/sasview/pull/2754.

The one change to the caveats, when the paired PR is merged into 6.0.0_release this will need to be merged into the release_0.9.0 branch as well as master

**Review by butlerpd — CHANGES_REQUESTED** [review]
I just realized that the comments to the paired PR in https://github.com/SasView/sasview/pull/2754 actually require changes here as well. Basically removing the changes in that PR which are to a file that is no longer in that repo and making those changes to the file which is now in this repo as part of this PR

**Comment by caitwolf** [comment]
I made requested changes in the paired SasView PR and made sure those changes were reflected in the new file locations in sasdata (it looks like changes were made in both places which helped with this).

**Review by butlerpd — APPROVED** [review]
Never mind... I didn't see the changes were made twice

**Pull request merged**
